version: '3.8'

services:
  sqlserver:
    container_name: pdf-sqlserver
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    ports:
      - "6467:1433"
    networks:
      - pdf_network
  
  webapp:
    container_name: pdf-webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - pdf_network

networks:
  pdf_network:
    driver: bridge