FROM mcr.microsoft.com/azure-sql-edge

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Password123!

# Crear directorio para scripts de inicialización
WORKDIR /scripts
COPY ./docker/sqlserver/init/01-init.sql /scripts/init.sql

EXPOSE 1433